
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthias
 */
public class ANLAGENVZ_AddDlg extends javax.swing.JDialog {

    /**
     * Creates new form ANLAGENVZ_AddDlg
     */
    private ANLAGENVZ_Anlage a = null;
    private boolean ok = false;
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    
    public ANLAGENVZ_AddDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfBezeichnung = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAW = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfInbetriebnahme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfND = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bezeichnung:");
        getContentPane().add(jLabel1);

        tfBezeichnung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfBezeichnung.setText("Software");
        getContentPane().add(tfBezeichnung);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Anschaffungswert:");
        getContentPane().add(jLabel2);

        tfAW.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAW.setText("80000");
        getContentPane().add(tfAW);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Inbetriebnahme:");
        getContentPane().add(jLabel3);

        tfInbetriebnahme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfInbetriebnahme.setText("2015.5");
        getContentPane().add(tfInbetriebnahme);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Nutzungsdauer in Jahren:");
        getContentPane().add(jLabel4);

        tfND.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfND.setText("8");
        getContentPane().add(tfND);

        btOk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        getContentPane().add(btOk);

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btCancel.setText("ABBRECHEN");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try{
            a = new ANLAGENVZ_Anlage(tfBezeichnung.getText(),Double.parseDouble(tfAW.getText()),Double.parseDouble(tfInbetriebnahme.getText()),Integer.parseInt(tfND.getText()));
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        ok=true;
        this.dispose();
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        ok=false;
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    public boolean isOk(){
        return ok;
    }
    
    public ANLAGENVZ_Anlage getAnlage(){
        return a;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ANLAGENVZ_AddDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ANLAGENVZ_AddDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ANLAGENVZ_AddDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ANLAGENVZ_AddDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ANLAGENVZ_AddDlg dialog = new ANLAGENVZ_AddDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfAW;
    private javax.swing.JTextField tfBezeichnung;
    private javax.swing.JTextField tfInbetriebnahme;
    private javax.swing.JTextField tfND;
    // End of variables declaration//GEN-END:variables
}
